### PR TITLE
chore(cicd): add build and release-pypi workflows

### LINKED ISSUE #6: CI/CD Workflows
Add CI/CD workflows for linting, building, testing, and publishing to PyPI.  Initial linting stage can fail as there are currently linting issues within the code.

### PR DESCRIPTION
**Pull request by keatincf**
Closes #6 

Creates build and release-pypi workflows.  Build workflow is run against all pull request and the main branch.  Build will lint, test, and run semantic release.  A package from the build will be stored for later use.  Semantic release won't actually generate a new release on a pull request (semantic release configuration, not part of the workflow), but will on changes to main.

When semantic release creates a release commit on main, the release-pypi will generate a Github release of the released code and then publsih to PyPI.  The package published to PyPI is the package generated by the build workflow, which ensures that the package being published is generated by the code that was tested.

### CODE REVIEW

**Comment by keatincf** [comment]
The project will need to have an environment named "release" added to be able to publish to PyPI.  The environment will need to have a variable named "RELEASE_TOKEN".  That variable should be an access token with public_repo access to allow the semantic release to push a commit to main.

I don't have permissions to create the environment for this project, although I can modify some project settings.

**Comment by keatincf** [comment]
Markdown linting currently will show errors in CHANGELOG.md.  I'm letting this go for now as the update_2023 branch will handle introducing the ignore file for Markdownlint.

**Review by jamie-cunningham — APPROVED** [review]
Looks straightforward and good to me

**Comment by jamie-cunningham** [comment]
> The project will need to have an environment named "release" added to be able to publish to PyPI. The environment will need to have a variable named "RELEASE_TOKEN". That variable should be an access token with public_repo access to allow the semantic release to push a commit to main.
> 
> I don't have permissions to create the environment for this project, although I can modify some project settings.

Environment and token have been set up

**Pull request merged**
